name = "solar-theme-hugo"
license = "GPLv2"
licenselink = "https://github.com/bake/solar-theme-hugo/blob/master/LICENSE.md"
description = ""
homepage = "https://github.com/bake/solar-theme-hugo"
tags = []
features = []
min_version = "0.25.1"

[author]
	name = "bake"
	homepage = "https://192k.pw/"

[original]
	name = "solar-theme-ghost"
	homepage = "https://github.com/bake/solar-theme-ghost"
	repo = "https://github.com/bake/solar-theme-ghost"
