title = "Solar Theme"
theme = "solar-theme-hugo"
paginate = 2

[params]
  scheme = "dark"
  description = "A wizard is never late"

[menu]
  [[menu.main]]
    name = "Feed"
    url = "/index.xml"
  [[menu.main]]
    name = "Repository"
    url = "https://github.com/bake/solar-theme-hugo"
  [[menu.other]]
    name = "Hugo"
    url = "https://themes.gohugo.io/solar-theme-hugo/"
  [[menu.other]]
    name = "Demo"
    url = "https://themes.gohugo.io/theme/solar-theme-hugo/"
